import { SimulationProvider } from '../context/SimulationContext';
import "./globals.css";

// TODO: keep?
/*
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <SimulationProvider>
                    { children }
                </SimulationProvider>
            </body>
        </html>
    );
}
